collections:
  - name: "pages"
    label: "Pages"
    files:

      - label: "Home Page"
        name: "home"
        file: "content/home.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }

      - label: "About Page"
        name: "about"
        file: "content/about.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }

      - label: "Contact Page"
        name: "contact"
        file: "content/contact.json"
        fields:
          - { label: "Email", name: "email", widget: "string" }
